### ISSUE TITLE
Random Order of entries

### ISSUE THREAD

**Issue by simonblau** [custom-components/sensor.feedparser#6]
Hey Ian, 

i don't know, if this is an issue, but the order of entries in my feed seems to be absolutely random (?). In the original code they are sorted bei publishing date, but in Home Assistant, they aren't and they aren't sorted by Alphabet, too. 

Greetings from Germany,
Simon

**Comment by iantrich** [comment]
They will be in the same order as the feed. Now additional sorting is done

**Comment by simonblau** [comment]
This is the source: [https://siftrss.com/f/pRDLGWvYQm](url)

And this is what my feed entity contains (i highlighted the Dates for you), it's not the same order:

Kerzen-Recycling für die umweltbewusste Weihnachtsstimmung: {
  "title_detail": {
    "type": "text/plain",
    "value": "Rotes Teelicht",
    "language": null,
    "base": "http://www.bund.net/"
  },
  "tags": [
    {
      "label": null,
      "term": "Ressourcen & Technik",
      "scheme": null
    },
    {
      "label": null,
      "term": "Nachhaltigkeit",
      "scheme": null
    }
  ],
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/kerzen-recycling-fuer-die-umweltbewusste-weihnachtsstimmung/"
    }
  ],
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/teelicht_oekotipp.jpg",
  "title": "Kerzen-Recycling für die umweltbewusste Weihnachtsstimmung",
  **"published": "Fri, Dec 14 01:35 PM",**
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/kerzen-recycling-fuer-die-umweltbewusste-weihnachtsstimmung/"
}
Kleine Lampenkunde: {
  "title_detail": {
    "type": "text/plain",
    "value": "Evolution der Beleuchtung von der Kerze zur Energiesparlampe; Foto: © vladimirfloyd - Fotolia.com",
    "language": null,
    "base": "http://www.bund.net/"
  },
  "tags": [
    {
      "label": null,
      "term": "Energiewende",
      "scheme": null
    },
    {
      "label": null,
      "term": "Klimawandel",
      "scheme": null
    },
    {
      "label": null,
      "term": "Ressourcen & Technik",
      "scheme": null
    },
    {
      "label": null,
      "term": "Nachhaltigkeit",
      "scheme": null
    }
  ],
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/das-1x1-der-energiesparlampe/"
    }
  ],
  "href": "https://www.bund.net/fileadmin/_processed_/7/a/csm_energiesparlampen_0873bf87de.jpg",
  "title": "Kleine Lampenkunde",
  **"published": "Wed, Aug 29 12:00 AM",**
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/das-1x1-der-energiesparlampe/"
}
Wäschewaschen mit Rosskastanien: {
  "title_detail": {
    "type": "text/plain",
    "value": "Rosskastanien; Foto: Couleur",
    "language": null,
    "base": "http://www.bund.net/"
  },
  "tags": [
    {
      "label": null,
      "term": "Chemie",
      "scheme": null
    },
    {
      "label": null,
      "term": "Flüsse & Gewässer",
      "scheme": null
    },
    {
      "label": null,
      "term": "Ressourcen & Technik",
      "scheme": null
    },
    {
      "label": null,
      "term": "Nachhaltigkeit",
      "scheme": null
    },
    {
      "label": null,
      "term": "Suffizienz",
      "scheme": null
    },
    {
      "label": null,
      "term": "Umweltgifte",
      "scheme": null
    }
  ],
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/waeschewaschen-mit-rosskastanien/"
    }
  ],
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/rosskastanie_by_couleur.jpg",
  "title": "Wäschewaschen mit Rosskastanien",
  **"published": "Wed, Dec 12 10:03 AM",**
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/waeschewaschen-mit-rosskastanien/"
}
Besser beleuchten – Sternenzelt statt Lichtersmog: {
  "title_detail": {
    "type": "text/plain",
    "value": "Dorfbeleuchtung vor-und nach Beleuchtungsverbesserung",
    "language": null,
    "base": "http://www.bund.net/"
  },
  "tags": [
    {
      "label": null,
      "term": "Nachhaltigkeit",
      "scheme": null
    },
    {
      "label": null,
      "term": "Energiewende",
      "scheme": null
    },
    {
      "label": null,
      "term": "Ressourcen & Technik",
      "scheme": null
    },
    {
      "label": null,
      "term": "Naturschutz",
      "scheme": null
    }
  ],
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/besser-beleuchten-sternenzelt-statt-lichtersmog/"
    }
  ],
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/dorfbeleuchtung_oekotipp.jpg",
  "title": "Besser beleuchten – Sternenzelt statt Lichtersmog",
  **"published": "Wed, Dec 12 04:31 PM",**
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/besser-beleuchten-sternenzelt-statt-lichtersmog/"
}
icon: mdi:rss
Umweltbewusst online einkaufen: {
  "title_detail": {
    "type": "text/plain",
    "value": "Onlineshopping; Foto: iStock.com / mangpor_2004",
    "language": null,
    "base": "http://www.bund.net/"
  },
  "tags": [
    {
      "label": null,
      "term": "Ressourcen & Technik",
      "scheme": null
    },
    {
      "label": null,
      "term": "Nachhaltigkeit",
      "scheme": null
    },
    {
      "label": null,
      "term": "Suffizienz",
      "scheme": null
    },
    {
      "label": null,
      "term": "Mobilität",
      "scheme": null
    }
  ],
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/umweltbewusst-online-einkaufen/"
    }
  ],
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/onlineshopping.jpg",
  "title": "Umweltbewusst online einkaufen",
  **"published": "Tue, Oct 30 04:38 PM",**
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/umweltbewusst-online-einkaufen/"
}
Plastikfrei feiern: {
  "title_detail": {
    "type": "text/plain",
    "value": "Festmahl. Foto: RealAKP / pixabay.com",
    "language": null,
    "base": "http://www.bund.net/"
  },
  "tags": [
    {
      "label": null,
      "term": "Nachhaltigkeit",
      "scheme": null
    },
    {
      "label": null,
      "term": "Ressourcen & Technik",
      "scheme": null
    },
    {
      "label": null,
      "term": "Naturschutz",
      "scheme": null
    },
    {
      "label": null,
      "term": "Chemie",
      "scheme": null
    }
  ],
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/plastikfrei-feiern/"
    }
  ],
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/karpfen_essen.jpg",
  "title": "Plastikfrei feiern",
  **"published": "Thu, Aug 30 11:06 AM",**
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/plastikfrei-feiern/"
}
friendly_name: Feed Nachhaltigkeit

**Comment by iantrich** [comment]
Works fine for me

```json
Kerzen-Recycling für die umweltbewusste Weihnachtsstimmung: {
  "title": "Kerzen-Recycling für die umweltbewusste Weihnachtsstimmung",
  "title_detail": {
    "type": "text/plain",
    "language": null,
    "base": "http://www.bund.net/",
    "value": "Rotes Teelicht"
  },
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/kerzen-recycling-fuer-die-umweltbewusste-weihnachtsstimmung/"
    }
  ],
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/kerzen-recycling-fuer-die-umweltbewusste-weihnachtsstimmung/",
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/teelicht_oekotipp.jpg",
  "tags": [
    {
      "term": "Ressourcen & Technik",
      "scheme": null,
      "label": null
    },
    {
      "term": "Nachhaltigkeit",
      "scheme": null,
      "label": null
    }
  ],
  "published": "Fri, Dec 14 01:35 PM"
}
Besser beleuchten – Sternenzelt statt Lichtersmog: {
  "title": "Besser beleuchten – Sternenzelt statt Lichtersmog",
  "title_detail": {
    "type": "text/plain",
    "language": null,
    "base": "http://www.bund.net/",
    "value": "Dorfbeleuchtung vor-und nach Beleuchtungsverbesserung"
  },
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/besser-beleuchten-sternenzelt-statt-lichtersmog/"
    }
  ],
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/besser-beleuchten-sternenzelt-statt-lichtersmog/",
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/dorfbeleuchtung_oekotipp.jpg",
  "tags": [
    {
      "term": "Nachhaltigkeit",
      "scheme": null,
      "label": null
    },
    {
      "term": "Energiewende",
      "scheme": null,
      "label": null
    },
    {
      "term": "Ressourcen & Technik",
      "scheme": null,
      "label": null
    },
    {
      "term": "Naturschutz",
      "scheme": null,
      "label": null
    }
  ],
  "published": "Wed, Dec 12 04:31 PM"
}
Wäschewaschen mit Rosskastanien: {
  "title": "Wäschewaschen mit Rosskastanien",
  "title_detail": {
    "type": "text/plain",
    "language": null,
    "base": "http://www.bund.net/",
    "value": "Rosskastanien; Foto: Couleur"
  },
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/waeschewaschen-mit-rosskastanien/"
    }
  ],
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/waeschewaschen-mit-rosskastanien/",
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/rosskastanie_by_couleur.jpg",
  "tags": [
    {
      "term": "Chemie",
      "scheme": null,
      "label": null
    },
    {
      "term": "Flüsse & Gewässer",
      "scheme": null,
      "label": null
    },
    {
      "term": "Ressourcen & Technik",
      "scheme": null,
      "label": null
    },
    {
      "term": "Nachhaltigkeit",
      "scheme": null,
      "label": null
    },
    {
      "term": "Suffizienz",
      "scheme": null,
      "label": null
    },
    {
      "term": "Umweltgifte",
      "scheme": null,
      "label": null
    }
  ],
  "published": "Wed, Dec 12 10:03 AM"
}
Umweltbewusst online einkaufen: {
  "title": "Umweltbewusst online einkaufen",
  "title_detail": {
    "type": "text/plain",
    "language": null,
    "base": "http://www.bund.net/",
    "value": "Onlineshopping; Foto: iStock.com / mangpor_2004"
  },
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/umweltbewusst-online-einkaufen/"
    }
  ],
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/umweltbewusst-online-einkaufen/",
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/onlineshopping.jpg",
  "tags": [
    {
      "term": "Ressourcen & Technik",
      "scheme": null,
      "label": null
    },
    {
      "term": "Nachhaltigkeit",
      "scheme": null,
      "label": null
    },
    {
      "term": "Suffizienz",
      "scheme": null,
      "label": null
    },
    {
      "term": "Mobilität",
      "scheme": null,
      "label": null
    }
  ],
  "published": "Tue, Oct 30 04:38 PM"
}
Plastikfrei feiern: {
  "title": "Plastikfrei feiern",
  "title_detail": {
    "type": "text/plain",
    "language": null,
    "base": "http://www.bund.net/",
    "value": "Festmahl. Foto: RealAKP / pixabay.com"
  },
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/plastikfrei-feiern/"
    }
  ],
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/plastikfrei-feiern/",
  "href": "https://www.bund.net/fileadmin/user_upload_bund/bilder/tipps/oekotipps/karpfen_essen.jpg",
  "tags": [
    {
      "term": "Nachhaltigkeit",
      "scheme": null,
      "label": null
    },
    {
      "term": "Ressourcen & Technik",
      "scheme": null,
      "label": null
    },
    {
      "term": "Naturschutz",
      "scheme": null,
      "label": null
    },
    {
      "term": "Chemie",
      "scheme": null,
      "label": null
    }
  ],
  "published": "Thu, Aug 30 11:06 AM"
}
Kleine Lampenkunde: {
  "title": "Kleine Lampenkunde",
  "title_detail": {
    "type": "text/plain",
    "language": null,
    "base": "http://www.bund.net/",
    "value": "Evolution der Beleuchtung von der Kerze zur Energiesparlampe; Foto: © vladimirfloyd - Fotolia.com"
  },
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "https://www.bund.net/bund-tipps/detail-tipps/tip/das-1x1-der-energiesparlampe/"
    }
  ],
  "link": "https://www.bund.net/bund-tipps/detail-tipps/tip/das-1x1-der-energiesparlampe/",
  "href": "https://www.bund.net/fileadmin/_processed_/7/a/csm_energiesparlampen_0873bf87de.jpg",
  "tags": [
    {
      "term": "Energiewende",
      "scheme": null,
      "label": null
    },
    {
      "term": "Klimawandel",
      "scheme": null,
      "label": null
    },
    {
      "term": "Ressourcen & Technik",
      "scheme": null,
      "label": null
    },
    {
      "term": "Nachhaltigkeit",
      "scheme": null,
      "label": null
    }
  ],
  "published": "Wed, Aug 29 12:00 AM"
}
friendly_name: eed Nachhaltigkeit
icon: mdi:rss
```

with the config
```yaml
sensor:
  - platform: feedparser
    name: eed Nachhaltigkeit
    feed_url: 'https://siftrss.com/f/pRDLGWvYQm'
    date_format: '%a, %b %d %I:%M %p'
```
