### ISSUE TITLE
Feedparser breaks Drone.io

### ISSUE THREAD

**Issue by ikifar2012** [custom-components/sensor.feedparser#8]
On my internal network I have a CI server that tests my home assistant config. I have noticed the Feedparser sensor always causes my CI server to fail. Feedparser did fail when I first installed it on my main HA but after a second reboot it started working. I was wondering if anyone else has this issue and if it can be fixed so it works on first boot

**Comment by ikifar2012** [comment]
```yaml
Testing configuration at /drone/src/.
Failed config
  General Errors: 
    - Platform not found: sensor.feedparser

Successful config (partial)
```

**Comment by iantrich** [comment]
From the README
![image](https://user-images.githubusercontent.com/1287159/51861909-08bd2b80-2303-11e9-8f31-b6015e62865b.png)

**Comment by ikifar2012** [comment]
> From the README
> ![image](https://user-images.githubusercontent.com/1287159/51861909-08bd2b80-2303-11e9-8f31-b6015e62865b.png)

is there anyway home assistant can fix this? is there anyway for me to get drone to succeed?

**Comment by iantrich** [comment]
I have no idea. @ludeeus do you have any insight into this?

**Comment by ludeeus** [comment]
Add the dependent external package to a requirements.txt file that the CI installs before running tests.

**Comment by ikifar2012** [comment]
> Add the dependent external package to a requirements.txt file that the CI installs before running tests.

How?

**Comment by ludeeus** [comment]
I did not see anything on their site for it, but it should be possible, I have loaded multiple custom components with both Travis and gitlab CI, and never seen this issue with them

**Comment by ikifar2012** [comment]
What are the requirements needed for this component I have ``feedparser==5.2.1`` in my requirements but it still does not work

**Comment by ikifar2012** [comment]
Nevermind I have fixed the issue by re installing my custom component and adding `feedparser==5.2.1` in requirements if anyone else runs into this issue feel free to check out my Home Assistant config on Github for the requirements.txt file
